### ISSUE TITLE
I would like to get involved, but where's the plan?

### ISSUE THREAD

**Issue by scphantm** [resumic/schema#71]
This project and jsonresume have my interest peaked.  I would like to get involved, but i don't see any kind of roadmap or anything of the like.

I have been reading for over an hour now and i think i have things figured out, let me know how well i did:

- the original maintainers of jsonresume went dark and no one has access to the servers to deploy updated versions of the code.
- This crew took the original jsonresume and begin building a formal schema
- Instead of simply maintaining a schema file, you are writing a go program that uses doodads in Go in order to generate the official schema file itself.  That's what this program is.

Now once the schema is done, this would be considered jsonresume v2 basically.

- Ok, so once thats done, then what?   
- Do you plan on writing a new generation platform in go?
- Do you plan on bringing over the jsonresume stuff and redeploying updated versions under the resumic name?

There are over 278 existing templates built on jsonresume code, it would be a shame to toss all that.  I can get started on getting new versions of things deployed and such, i just need to know what the plan is.

**Comment by stp-ip** [comment]
There is no public roadmap as we are still iterating with each step.
To summarize:
* PoC schema (done)
* minimal tooling to get some user feedback for schema
* iterate on schema
* contribute schema to jsonresume
* iterate tooling in parallel within jsonresume (JS based) and resumic (Go based)

> To answer the rest inline:
> I have been reading for over an hour now and i think i have things figured out, let me know how well i did:
> 
>     the original maintainers of jsonresume went dark and no one has access to the servers to deploy updated versions of the code.
Yes most of the maintainers went dark. Server access and support were problematic. Seems like one came back, but even reaching out multiple times, I couldn't get any response still.

>     This crew took the original jsonresume and begin building a formal schema
Me personally I am and was a maintainer helping out at jsonresume, but it felt faster to iterate separately and contribute our findings back.

>     Instead of simply maintaining a schema file, you are writing a go program that uses doodads in Go in order to generate the official schema file itself. That's what this program is.
Yes instead of having multiple files that need to be kept in sync, we are trying to have one single source of truth in Go, that generates the schema, example and later documentation.

Felt like the more maintainable way in the long run. Also in terms of not just supporting jsonschema, if it ever comes to that.

This program is still a WIP and therefore we are still iterating on the structure. We are happy for you to jump into any discussions etc. I can also invite you to our basecamp for faster syncs.

> 
> Now once the schema is done, this would be considered jsonresume v2 basically.
> 
>     Ok, so once thats done, then what?
Contribute the schema back and try to make both platforms compatible from a data perspective.

>     Do you plan on writing a new generation platform in go?
We have a PoC of a hugo based rendering platform. So within resumic we want to add a rendering platform, a client based and hosted editor and some further ideas in the long run.

>     Do you plan on bringing over the jsonresume stuff and redeploying updated versions under the resumic name?
Bringing over ideas and maybe theme designs. We want to take the chance to learn from the old code, without doing a simple rewrite.

> There are over 278 existing templates built on jsonresume code, it would be a shame to toss all that. I can get started on getting new versions of things deployed and such, i just need to know what the plan is.
As we hope that jsonresume would be compatible with the new schema these don't even have to be migrated. A few interesting ones could be migrated and then made Hugo (resumic) native, if it makes sense.

Looking forward to collaborate. \o/

**Comment by scphantm** [comment]
all this makes sense.  Now, i want to suggest a change to the schema in an MR, but i think i found a major issue with your technique in GO.  How do you define definitions and complex ifs?  for example, this is a common pattern

```
  "assetMetadata": {
    "type": "object",
    "additionalProperties": false,
    "properties": { ... }
  }
```

and 

```
  "assetMetadata": [{
    "type": "object",
    "additionalProperties": false,
    "properties": { ... }
  }]
```
 begin equivalent.  The first one, when rendered to pojo's, is deserialized as an array of one object.  This is a piece of cake to define in json schema

```
{
  "type": "object",
  "properties": {
    "assetMetadata": {
      "anyOf": [
        { "$ref": "#/definitions/assetMetaData" },
        {
          "type": "array",
          "description": "...",
          "items": { "#/definitions/assetMetaData" }
        }
      ]
    }
  },
  "definitions": {
    "assetMetadata": {
      "type": "object",
      "additionalProperties": false,
      "properties": { ... }
    }
  }
}
```
but reading the docs it looks like you used to generate the GO program, its capable of reading and validating this type of schema, but it doesn't look like its able to generate that type of schema.  

I've done exactly what you are attempting before, only difference is i maintained a master json schema file, then wrote a simple python script that generated the docs and example based on the master file.  This week i will convert this one and show you what i mean.  but right now, it doesn't look like i can do some of the things i want to be able to do with the GO program.

**Comment by ArmanMazdaee** [comment]
Sorry, but I didn't quite understand what you want to achieve. May you please describe more specifically the change you want to make so I could help with the solution?

**Comment by stp-ip** [comment]
Please reopen with more information so we can help better.
